Install pygobject and its dependency, pycairo
Because a project that uses elementary Flatpak Platform with
blueprint-compiler fails to build without it, which was probably
included in GNOME Flatpak Platform:

    Found ninja-1.13.2 at /usr/bin/ninja
    [1/50] Generating data/blueprints with a custom command
    FAILED: [code=1] data
    /app/bin/blueprint-compiler batch-compile data/. ../data ../data/ui/help-overlay.blp
    Traceback (most recent call last):
      File "/app/bin/blueprint-compiler", line 40, in <module>
        from blueprintcompiler import main
      File "/app/lib/python3.13/site-packages/blueprintcompiler/main.py", line 27, in <module>
        from . import formatter, interactive_port, linter, parser, tokenizer
      File "/app/lib/python3.13/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
        from . import decompiler, parser, tokenizer
      File "/app/lib/python3.13/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
        from .gir import *
      File "/app/lib/python3.13/site-packages/blueprintcompiler/gir.py", line 25, in <module>
        import gi  # type: ignore
        ^^^^^^^^^
    ModuleNotFoundError: No module named 'gi'
    [2/50] Merging translations for data/com.github.ryonakano.reco.Devel.metainfo.xml
    ninja: build stopped: subcommand failed.