actions: Update to Ubuntu 24.04 runners
Because flat-manager-client now requires libc >= 2.38 that is not
available on jammy:

    Run BUILD_ID=`flat-manager-client create https://flatpak-api.elementary.io appcenter`
    flat-manager-client: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by flat-manager-client)
    Error: Process completed with exit code 1.